global:
  scrape_interval: 10s # Server 抓取頻率
  external_labels:
    monitor: "my-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["172.31.11.47:9113"]
  - job_name: "linux"
    static_configs:
      - targets: ["172.31.11.47:9100"]
