global:
  scrape_interval: 5s # Server 抓取頻率
  external_labels:
    monitor: "my-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nginx"
    static_configs:
      - targets: ["172.31.11.47:9113"]
  - job_name: "node"
    static_configs:
      - targets:
          [
            "172.31.11.47:9100",
            "172.31.27.157:9100",
            "172.31.18.169:9100",
            "172.31.31.112:9100",
          ]
  - job_name: "kafka"
    static_configs:
      - targets: ["172.31.27.157:7071"]
